### ISSUE TITLE
Influenza subtypes galaxy pipeline and tutorial

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/Avans-ATGM.github.io#1]
- [x] Testing pipeline
- [x] Updated and adjusted pipeline for new galaxy server
- [x] meeting eefje understanding parts of workflow. 

--- updates 17-01-2022
I had a meeting with Eefje and she would like to see this pipeline grow but can also be a non galaxy pipeline
In P3 and P4 she will have a new intern who will work with this kind of data. One of his tasks will be upgrading  the pipeline. The pipeline should be tested with other viruses and databases.

Priority task : none

- [ ] Student will improve/add tools to the pipeline
- [ ] test pipeline with other viruses amplicon analyses
- [ ] add phylogenetic tree analysis
- [ ] add MLST
- [ ] {{ other ideas to add to the pipeline }}

**Comment by Dirowa** [comment]
- [x] Testing pipeline
- [x] Working out Tutorial for students to follow (Not nessacary anymore according eefje
- [x] Updated and adjusted pipeline for new galaxy server
- [x] meeting eefje understanding parts of workflow.

**Comment by hexylena** [comment]
be sure to use this to make the tutorial building faster :) https://ptdk.herokuapp.com/

**Comment by Dirowa** [comment]
Becomming stale. Work is transferred to new intern of Eefje
